version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      context: .              
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    restart: always

